[build]
    publish = '_site'
    command = 'npm run build'

[[redirects]]
  from = "/sites/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/redirect-to-random-site-url"
  to = "/.netlify/functions/redirect-to-random-site-url"
  status = 200
